name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Android SDK
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y wget unzip lib32stdc++6 lib32z1
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/Android
          mv $HOME/Android/cmdline-tools $HOME/Android/cmdline-tools-latest
          yes | $HOME/Android/cmdline-tools-latest/bin/sdkmanager --licenses
          $HOME/Android/cmdline-tools-latest/bin/sdkmanager --update
          $HOME/Android/cmdline-tools-latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Set Android SDK environment variable
        run: echo "ANDROID_SDK_ROOT=$HOME/Android" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK (Debug)
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: app/build/test-results/testDebugUnitTest/*.xml
