name: Android CI/CD Pipeline

on:
  push:
    branches:
      - main  # Срабатывает при push на ветку main
  pull_request:
    branches:
      - main  # Срабатывает при pull request в ветку main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'      # <--- ВАЖНО: добавлено!
          java-version: '11'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Run tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'      # <--- тоже добавлено!
          java-version: '11'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build the project
        run: ./gradlew build
